# Generated by Django 3.0.3 on 2020-04-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='Link',
            field=models.URLField(blank=True),
        ),
    ]
