# Generated by Django 3.0.3 on 2020-04-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_auto_20200410_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Year', models.IntegerField(blank=True, max_length=4)),
                ('Genre', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
